config/routes.rb
Rails.application.routes.draw do
  get    '/' => 'posts#top'
  get    '/posts' => 'posts#index'
  post   'posts' => 'posts#create'
  get    '/posts/:id' => 'posts#show', as: 'post'
  get    '/posts/:id/edit' => 'posts#edit', as: 'edit_post'
  patch  '/posts/:id' => 'posts#update', as: 'update_post'
  delete '/posts/:id' => 'posts#destroy', as: 'destroy_post'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def top
  end

  def index
    @posts = Post.all
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Book was successfully created."
      redirect_to post_path(@post)
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
       flash[:notice] = "Book was successfully update."
       redirect_to post_path(post)
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      flash[:notice] = "Book was successfully desroyed."
      redirect_to posts_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@post) do |f| %>
<div class="field">
  <%= f.label :Title %>
  <%= f.text_field :title, class: "book_title" %>
</div>
<div class="field">
  <%= f.label :Body %>
  <%= f.text_area :body, class: "book_body" %>
</div>
<div class="actions">
   <%= f.submit 'Create Book' %>
</div>
<% end %>

<%= link_to 'Show',post_path, class: "show_#{@post.id}" %>
|
<%= link_to 'Back',posts_path, class: "back" %>

app/views/posts/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
 </thead>

<% @posts.each do |post| %>
 <tdoby>
   <tr>
     <td><%= post.title %></td>
     <td><%= post.body %></td>
     <td><%= link_to 'Show', post_path(post), class: "show_#{post.id}" %></td>
     <td><%= link_to 'Edit', edit_post_path(post), class: "edit_#{post.id}" %></td>
     <td><%= link_to 'Destroy', post_path(post), method: :delete, class: "destroy_#{post.id}" %></td>
   </tr>
 </tbody>
<% end %>
</table>
<!-- form_for部分 -->
<h2>New book</h2>
<%= form_for(@post) do |f| %>
 <div class="field">
   <%= f.label :Title %>
   <%= f.text_field :title, class: "book_title" %>
 </div>
 <div class="field">
   <%= f.label :Body %>
   <%= f.text_area :body, class: "book_body" %>
 </div>
 <div class="actions">

   <%= f.submit 'Create Book' %>
 </div>
<% end %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit',edit_post_path, class: "edit_#{@post.id}" %>
|
<%= link_to 'Back',posts_path, class: "back" %>

app/views/posts/top.html.erb
<h1>ようこそ <strong>Bookers</strong> へ！</h1>
<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
</p>
<p>
  印象を共有し交換することができます
</p>
<p>
  <%= link_to "start", posts_path %>
</p>